sudo: required
services:
   - docker

before_install:
   - docker build -t ikb4r/docker-react -f Dockerfile.dev .

script:
   - docker run ikb4r/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-us-east-1-284453997941"
   bucket-path: "docker-react"